const radarStationInfo = {
    KDIX: { name: 'Philadelphia', type: 'WSR-88D' },
    KSJT: { name: 'San Angelo', type: 'WSR-88D' },
    KLOT: { name: 'Chicago', type: 'WSR-88D' },
    KFTG: { name: 'Denver', type: 'WSR-88D' },
    TTUL: { name: 'Tulsa', type: 'TDWR' },
    KEYX: { name: 'Edwards AFB', type: 'WSR-88D' },
    TTPA: { name: 'Tampa Bay', type: 'TDWR' },
    KBUF: { name: 'Buffalo', type: 'WSR-88D' },
    KDFX: { name: 'Laughlin AFB', type: 'WSR-88D' },
    KGRK: { name: 'Ft Hood', type: 'WSR-88D' },
    KSGF: { name: 'Springfield', type: 'WSR-88D' },
    KHGX: { name: 'Houston', type: 'WSR-88D' },
    KSRX: { name: 'Western Arkansas', type: 'WSR-88D' },
    KCAE: { name: 'Columbia', type: 'WSR-88D' },
    KAMX: { name: 'Miami', type: 'WSR-88D' },
    TJFK: { name: 'New York City', type: 'TDWR' },
    KCCX: { name: 'State College', type: 'WSR-88D' },
    KDDC: { name: 'Dodge City', type: 'WSR-88D' },
    KVBX: { name: 'Vandenberg AFB', type: 'WSR-88D' },
    TPIT: { name: 'Pittsburgh', type: 'TDWR' },
    TMDW: { name: 'Chicago Midway', type: 'TDWR' },
    KBBX: { name: 'Beale AFB', type: 'WSR-88D' },
    KCBW: { name: 'Caribou', type: 'WSR-88D' },
    KMLB: { name: 'Melbourne', type: 'WSR-88D' },
    KMBX: { name: 'Minot AFB', type: 'WSR-88D' },
    RKSG: { name: 'Camp Humphreys', type: 'WSR-88D' },
    KGRB: { name: 'Green Bay', type: 'WSR-88D' },
    KDMX: { name: 'Des Moines', type: 'WSR-88D' },
    KEVX: { name: 'Eglin Afb', type: 'WSR-88D' },
    KESX: { name: 'Las Vegas', type: 'WSR-88D' },
    KOTX: { name: 'Spokane', type: 'WSR-88D' },
    KRIW: { name: 'Riverton/Lander', type: 'WSR-88D' },
    THOU: { name: 'Houston Hobby', type: 'TDWR' },
    TMEM: { name: 'Memphis', type: 'TDWR' },
    KGWX: { name: 'Columbus AFB', type: 'WSR-88D' },
    KIWX: { name: 'Northern Indiana', type: 'WSR-88D' },
    KGGW: { name: 'Glasgow', type: 'WSR-88D' },
    TSLC: { name: 'Salt Lake City', type: 'TDWR' },
    KVNX: { name: 'Vance AFB', type: 'WSR-88D' },
    KPOE: { name: 'Ft Polk', type: 'WSR-88D' },
    KFFC: { name: 'Atlanta', type: 'WSR-88D' },
    KSHV: { name: 'Shreveport', type: 'WSR-88D' },
    KVAX: { name: 'Moody AFB', type: 'WSR-88D' },
    TEWR: { name: 'Newark', type: 'TDWR' },
    KLRX: { name: 'Elko', type: 'WSR-88D' },
    KCXX: { name: 'Burlington', type: 'WSR-88D' },
    KBIS: { name: 'Bismarck', type: 'WSR-88D' },
    KHNX: { name: 'San Joaquin Valley', type: 'WSR-88D' },
    KLWX: { name: 'Sterling', type: 'WSR-88D' },
    KOAX: { name: 'Omaha', type: 'WSR-88D' },
    KFCX: { name: 'Roanoke', type: 'WSR-88D' },
    KCRP: { name: 'Corpus Christi', type: 'WSR-88D' },
    KMAF: { name: 'Midland/Odessa', type: 'WSR-88D' },
    KCLE: { name: 'Cleveland', type: 'WSR-88D' },
    KFDR: { name: 'Altus AFB', type: 'WSR-88D' },
    KPDT: { name: 'Pendleton', type: 'WSR-88D' },
    TMSY: { name: 'New Orleans', type: 'TDWR' },
    TICH: { name: 'Witchita', type: 'TDWR' },
    KDGX: { name: 'Jackson/Brandon,MS', type: 'WSR-88D' },
    KTWX: { name: 'Topeka', type: 'WSR-88D' },
    KBGM: { name: 'Binghamton', type: 'WSR-88D' },
    KATX: { name: 'Seattle', type: 'WSR-88D' },
    PABC: { name: 'Bethel', type: 'WSR-88D' },
    KMTX: { name: 'Salt Lake City', type: 'WSR-88D' },
    TFLL: { name: 'Fort Lauderdale', type: 'TDWR' },
    KCBX: { name: 'Boise', type: 'WSR-88D' },
    KUEX: { name: 'Grand Island', type: 'WSR-88D' },
    TPBI: { name: 'West Palm Beach', type: 'TDWR' },
    KCLX: { name: 'Charleston,SC', type: 'WSR-88D' },
    TIAH: { name: 'Houston International', type: 'TDWR' },
    TBNA: { name: 'Nashville', type: 'TDWR' },
    KLVX: { name: 'Louisville', type: 'WSR-88D' },
    TDEN: { name: 'Denver', type: 'TDWR' },
    KPUX: { name: 'Pueblo', type: 'WSR-88D' },
    KLSX: { name: 'St Louis', type: 'WSR-88D' },
    KNKX: { name: 'San Diego', type: 'WSR-88D' },
    KVWX: { name: 'Evansville,IN', type: 'WSR-88D' },
    KMSX: { name: 'Missoula', type: 'WSR-88D' },
    TOKC: { name: 'Oklahoma City', type: 'TDWR' },
    KFDX: { name: 'Cannon AFB', type: 'WSR-88D' },
    KNQA: { name: 'Memphis', type: 'WSR-88D' },
    TDTW: { name: 'Detroit', type: 'TDWR' },
    KLZK: { name: 'Little Rock', type: 'WSR-88D' },
    KLCH: { name: 'Lake Charles', type: 'WSR-88D' },
    AWPA2: { name: 'Anchorage', type: 'Profiler' },
    PAIH: { name: 'Middleton Island', type: 'WSR-88D' },
    KMKX: { name: 'Milwaukee', type: 'WSR-88D' },
    PAKC: { name: 'King Salmon', type: 'WSR-88D' },
    KILN: { name: 'Cincinnati', type: 'WSR-88D' },
    PHWA: { name: 'South Shore', type: 'WSR-88D' },
    TLAS: { name: 'Las Vegas', type: 'TDWR' },
    KEWX: { name: 'Austin/San Antonio', type: 'WSR-88D' },
    TPHL: { name: 'Philadelphia', type: 'TDWR' },
    KTYX: { name: 'Ft Drum', type: 'WSR-88D' },
    KLNX: { name: 'North Platte', type: 'WSR-88D' },
    TDCA: { name: 'Washington National', type: 'TDWR' },
    KLBB: { name: 'Lubbock', type: 'WSR-88D' },
    PAEC: { name: 'Nome', type: 'WSR-88D' },
    TMCO: { name: 'Orlando International', type: 'TDWR' },
    KHPX: { name: 'Ft Campbell', type: 'WSR-88D' },
    TSJU: { name: 'San Juan', type: 'TDWR' },
    KRGX: { name: 'Reno', type: 'WSR-88D' },
    KMAX: { name: 'Medford', type: 'WSR-88D' },
    KICT: { name: 'Wichita', type: 'WSR-88D' },
    KDTX: { name: 'Detroit', type: 'WSR-88D' },
    KHDX: { name: 'Holloman AFB', type: 'WSR-88D' },
    KMOB: { name: 'Mobile', type: 'WSR-88D' },
    PHKM: { name: 'Kamuela/Kohala Apt', type: 'WSR-88D' },
    KMRX: { name: 'Knoxville', type: 'WSR-88D' },
    TDAY: { name: 'Dayton', type: 'TDWR' },
    KUDX: { name: 'Rapid City', type: 'WSR-88D' },
    KCYS: { name: 'Cheyenne', type: 'WSR-88D' },
    KVTX: { name: 'Los Angeles', type: 'WSR-88D' },
    KMHX: { name: 'Morehead City', type: 'WSR-88D' },
    KLIX: { name: 'Slidell', type: 'WSR-88D' },
    TDFW: { name: 'Dallas/Ft. Worth', type: 'TDWR' },
    KGJX: { name: 'Grand Junction', type: 'WSR-88D' },
    TMSP: { name: 'Minneapolis', type: 'TDWR' },
    KBYX: { name: 'Key West', type: 'WSR-88D' },
    KAPX: { name: 'NCL Michigan', type: 'WSR-88D' },
    KARX: { name: 'La Crosse', type: 'WSR-88D' },
    KMUX: { name: 'San Francisco', type: 'WSR-88D' },
    KDLH: { name: 'Duluth', type: 'WSR-88D' },
    KDOX: { name: 'Dover AFB', type: 'WSR-88D' },
    RKJK: { name: 'Kunsan AB', type: 'WSR-88D' },
    TBWI: { name: 'Baltimore/Wash', type: 'TDWR' },
    PAPD: { name: 'Fairbanks Faa', type: 'WSR-88D' },
    KSOX: { name: 'Santa Ana Mts', type: 'WSR-88D' },
    TRDU: { name: 'Raleigh Durham', type: 'TDWR' },
    KGSP: { name: 'Greer', type: 'WSR-88D' },
    KBLX: { name: 'Billings', type: 'WSR-88D' },
    KTFX: { name: 'Great Falls', type: 'WSR-88D' },
    TJUA: { name: 'San Juan', type: 'WSR-88D' },
    PGUA: { name: 'Andersen AFB', type: 'WSR-88D' },
    KMXX: { name: 'Maxwell AFB', type: 'WSR-88D' },
    KJKL: { name: 'Jackson,KY', type: 'WSR-88D' },
    KJGX: { name: 'Robins AFB', type: 'WSR-88D' },
    HWPA2: { name: 'Homer', type: 'Profiler' },
    KBOX: { name: 'Boston', type: 'WSR-88D' },
    KAMA: { name: 'Amarillo', type: 'WSR-88D' },
    TPHX: { name: 'Phoenix', type: 'TDWR' },
    RODN: { name: 'Kadena AB', type: 'WSR-88D' },
    KABR: { name: 'Aberdeen', type: 'WSR-88D' },
    KHTX: { name: 'Northeast Alabama', type: 'WSR-88D' },
    KIND: { name: 'Indianapolis', type: 'WSR-88D' },
    KTLH: { name: 'Tallahassee', type: 'WSR-88D' },
    KDVN: { name: 'Quad Cities', type: 'WSR-88D' },
    TMIA: { name: 'Miami', type: 'TDWR' },
    KMVX: { name: 'Fargo/Grand Forks', type: 'WSR-88D' },
    KBHX: { name: 'Eureka (Bunker Hill)', type: 'WSR-88D' },
    KJAX: { name: 'Jacksonville', type: 'WSR-88D' },
    TMCI: { name: 'Kansas City', type: 'TDWR' },
    TSDF: { name: 'Louisville,KY', type: 'TDWR' },
    KGRR: { name: 'Grand Rapids', type: 'WSR-88D' },
    KFSD: { name: 'Sioux Falls', type: 'WSR-88D' },
    KMQT: { name: 'Marquette', type: 'WSR-88D' },
    KLTX: { name: 'Wilmington', type: 'WSR-88D' },
    PHKI: { name: 'South Kauai', type: 'WSR-88D' },
    KRAX: { name: 'Raleigh/Durham', type: 'WSR-88D' },
    ROCO2: { name: 'Norman', type: 'Profiler' },
    PACG: { name: 'Sitka', type: 'WSR-88D' },
    KINX: { name: 'Tulsa', type: 'WSR-88D' },
    KEMX: { name: 'Tucson', type: 'WSR-88D' },
    KGYX: { name: 'Portland,ME', type: 'WSR-88D' },
    KIWA: { name: 'Phoenix', type: 'WSR-88D' },
    KRLX: { name: 'Charleston,WV', type: 'WSR-88D' },
    KEAX: { name: 'Pleasant Hill', type: 'WSR-88D' },
    PAHG: { name: 'Kenai', type: 'WSR-88D' },
    KSFX: { name: 'Pocatello', type: 'WSR-88D' },
    KTBW: { name: 'Tampa', type: 'WSR-88D' },
    TLKA2: { name: 'Talkeetna', type: 'Profiler' },
    KEOX: { name: 'Ft Rucker', type: 'WSR-88D' },
    TSTL: { name: 'St. Louis', type: 'TDWR' },
    KABX: { name: 'Albuquerque', type: 'WSR-88D' },
    KTLX: { name: 'Norman', type: 'WSR-88D' },
    TLVE: { name: 'Cleveland,OH', type: 'TDWR' },
    TMKE: { name: 'Milwaukee', type: 'TDWR' },
    KRTX: { name: 'Portland,OR', type: 'WSR-88D' },
    PHMO: { name: 'Molokai', type: 'WSR-88D' },
    KICX: { name: 'Cedar City', type: 'WSR-88D' },
    TORD: { name: "Chicago O'Hare", type: 'TDWR' },
    TDAL: { name: 'Dallas Love Field', type: 'TDWR' },
    KBRO: { name: 'Brownsville', type: 'WSR-88D' },
    KAKQ: { name: 'Norfolk', type: 'WSR-88D' },
    KBMX: { name: 'Birmingham', type: 'WSR-88D' },
    TBOS: { name: 'Boston', type: 'TDWR' },
    TADW: { name: 'Andrews Air Force Base', type: 'TDWR' },
    TCLT: { name: 'Charlotte', type: 'TDWR' },
    KYUX: { name: 'Yuma', type: 'WSR-88D' },
    KGLD: { name: 'Goodland', type: 'WSR-88D' },
    KDAX: { name: 'Sacramento', type: 'WSR-88D' },
    KENX: { name: 'Albany', type: 'WSR-88D' },
    TATL: { name: 'Atlanta', type: 'TDWR' },
    TCVG: { name: 'Covington', type: 'TDWR' },
    TIAD: { name: 'Dulles', type: 'TDWR' },
    KFWS: { name: 'Dallas/Ft Worth', type: 'WSR-88D' },
    KOHX: { name: 'Nashville', type: 'WSR-88D' },
    KEPZ: { name: 'El Paso', type: 'WSR-88D' },
    TCMH: { name: 'Columbus,OH', type: 'TDWR' },
    TIDS: { name: 'Indianapolis', type: 'TDWR' },
    KDYX: { name: 'Dyess AFB', type: 'WSR-88D' },
    KFSX: { name: 'Flagstaff', type: 'WSR-88D' },
    KPBZ: { name: 'Pittsburgh', type: 'WSR-88D' },
    KMPX: { name: 'Minneapolis', type: 'WSR-88D' },
    KOKX: { name: 'Brookhaven', type: 'WSR-88D' },
    KILX: { name: 'Lincoln', type: 'WSR-88D' },
    KPAH: { name: 'Paducah', type: 'WSR-88D' },
    KLGX: { name: 'Langley Hill', type: 'WSR-88D' }
}

module.exports = radarStationInfo;